### ISSUE TITLE
C'thun issues

### ISSUE THREAD

**Issue by birdayz** [Hosq/BigWigs#15]
When doing cthun yesterday, i faced some issues:

- [x] Cthun vulnerable phase was over after 1sec. I'm pretty sure this is caused by the 'alternate trigger for vuln phase'. I think it can be removed, we dont need it on elysium.
- [x] Dark Glare target announcement was wrong. i guess we also have to perform a delayed target check, as for the green beam.
- [ ] Giant Claw / Giant Eye tentacle timers were off. They are always at the same time when the little eye tentacles come, and +30s after the last giant tentacle. claw was first correct, but after some time later it was off by some seconds. need to investigate.

Also, tentacle timers were totally off but maybe this was just a consequence of the broken/aborted vulnerable phase.

**Comment by Hosq** [comment]
1. I agree alternate trigger for weaken can be removed and should fix the first problem.
2. Cthun is not actually targetting anyone when casting dark glare so id say that target announce can be removed aswell.
3. I watched some of our old kill videos and noticed that Giant Claw / Giant Eye do start correctly with small eyes but something causes them to reset at times. Could be fixed by removing useless triggers and using only ScheduleEvent for these like it is with small eyes.

Feel free to fix these if you have time and if not ill fix them later this week

**Comment by birdayz** [comment]
Yeah id like to work on it. Most likely on friday or the weekend.

**Comment by birdayz** [comment]
Ive taken a look at my video from sunday. in one case, the eye kept the target from before the glare cast. in another case, it casted green beam on a target, did not change target (as seen in unit frames) anymore until the glare cast, but did cast glare on a totally different target, which could not be seen on unit frames/targettarget. so it seems to me, sometimes the detection works, sometimes not. i would say, remove it if it is unreliable and we cant get it to work reliably, because people cant rely on it.
